create table public."Cashflow" (
  id bigint generated by default as identity not null,
  date date not null,
  category character varying null,
  description text null,
  amount integer null,
  type public.Cashflow Type not null default 'expense'::"Cashflow Type",
  "paymentMethod" public.PaymentMethod not null default 'cash'::"PaymentMethod",
  constraint Cashflow_pkey primary key (id)
) TABLESPACE pg_default;